name: Main
on:
  push:
    branches:
      - "*"
      
      
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
  call-workflow:
    needs: Prepare
    uses: thomas-shibin/github_action-commons/.github/workflows/commons-workflow.yaml@main
